version: "3.9"
services:
  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    networks:
      - tuxnetwork
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=tux123
      - MONGO_INITDB_DATABASE=phonebooking

networks:
  tuxnetwork:
    driver: bridge
