package link.yauritux.port.input.dto.response;

import com.fasterxml.jackson.annotation.JsonInclude;
import link.yauritux.domain.entity.BookingEntry;
import lombok.Builder;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * @author Yauri Attamimi (yauritux@gmail.com)
 * @version 1.0
 *
 * A response object type returned by the booking entry service.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@Data
@Builder
public class BookingEntryResponse {

    /**
     * a booking transaction id as generated by the repository system (e.g., database primary key auto generation)
     */
    String id;
    LocalDateTime bookedOn;
    LocalDateTime returnedOn;
    String phoneId;
    String deviceName;
    String technology;
    String _2gBands;
    private String _3gBands;
    private String _4gBands;
    private String userId;
    private String userName;
    private BookingEntry.BookingStatus status;
    /**
     * an error message contains explanation about the error if the booking request is failed.
     */
    private String errorMessage;
}
