server:
  port: ${SERVER_PORT}

spring:
  main:
    web-application-type: reactive
  data:
    mongodb:
      auto-index-creation: true
      uri: ${MONGO_DB_URI}
      authentication-database: admin

fonoapi:
  url: ${FONOAPI_URL}
  token: ${FONOAPI_TOKEN}
  timeout: ${FONOAPI_TIMEOUT_MS}

logging:
  level:
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health