server:
  port: ${SERVER_PORT}

spring:
  main:
    web-application-type: reactive
  data:
    mongodb:
      auto-index-creation: true
      uri: ${MONGO_DB_URI}
      authentication-database: admin

logging:
  level:
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health
